swagger: '2.0'
info:
  description: 'Sample Swagger file for REST Endpoints'
  version: 1.0.0
  title: API Store - your-service-name
  termsOfService: 'https://manulife.com/yourterms'
  contact:
    email: yourname@manulife.com
  license:
    name: Manulife Asia
    url: 'http://www.manulife.com'
host: yourservice.manulife.com
basePath: /api/v1
schemes:
  - https
paths:
  '/home':
    get:
      description: get all doctor
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: "#/definitions/HomeResponse"
definitions:
  Doctor:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      gender:
        type: "string"
  HomeResponse:
    type: "object"
    properties:
      answerEntity:
        type: "array"
        items:
          $ref: '#/definitions/Doctor'
        items:
          $ref: '#/definitions/Doctor'