swagger: '2.0'
info:
  description: 'AKS upskill - Rsf demo'
  version: 1.0.0
  title: 'Rsf demo'
  termsOfService: 'https://www.manulife.com/'
  contact:
    email: ngtszch@mfcgd.com
  license:
    name: Manulife Asia
    url: 'http://www.manulife.com'
host: 10.161.64.4
basePath: /James
schemes:
  - https
paths:
  '/home':
    get:
      description: get all doctor
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: "#/definitions/HomeResponse"
definitions:
  Doctor:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      gender:
        type: "string"
  HomeResponse:
    type: "object"
    properties:
      answerEntity:
        type: "array"
        items:
          $ref: '#/definitions/Doctor'
        items:
          $ref: '#/definitions/Doctor'