apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: drl-rsf-cn2-jamesng-demo
  namespace: ns-mua-training
spec:
  host: svc-rsf-cn2-jamesng-demo.ns-mua-training.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 30
        maxRequestsPerConnection: 100
    outlierDetection:
      consecutiveErrors: 3
      interval: 600ms
      baseEjectionTime: 10ms
      maxEjectionPercent: 100
  subsets:
  - name: v1
    labels:
      version: p1
