apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-rsf-connect-mongodb
  namespace: ns-mua-training
spec:
  hosts:
  - rsf-connect-mongodb.ns-mua-training
  - svc-rsf-connect-mongodb.ns-mua-training.svc.cluster.local
  gateways:
  - istio-system/istio-ingressgateway
  - mesh
  http:
  - name: rsf-connect-mongodb-route
    match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: svc-rsf-connect-mongodb.ns-mua-training.svc.cluster.local
        port:
          number: 8080
      weight: 100
    timeout: 800ms
    retries:
      attempts: 3
      perTryTimeout: 300ms
      retryOn: 5xx
